name: "AWS S3 Sync with CloudFront Cache invalidation"
description: "Sync a directory to an AWS S3 bucket and invalidate the CloudFront cache"
author: kersvers
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
